config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  mount ActionCable.server => '/cable'

  resources :participants

  namespace :v1 do
    resources :posts
  end

  namespace :v2 do
    resources :posts
  end

  namespace :v3 do
    resources :posts
  end

  namespace :v4 do
    resources :posts
  end

  namespace :v5 do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/participant.rb
class Participant < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :username, presence: {message: 'Come on! At least come up with a funny nickname!'}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :participant

  validates :text, length: {maximum: 256, message: 'So many emotions!!! But try to compress them down to 256 chars. ^_^'}
  validates :text, presence: {message: 'Nothing to share? :-('}

  validate :dont_spam

  after_create_commit -> { broadcast_render_to 'posts', partial: 'v4/posts/create', locals: {post: self} }
  after_destroy_commit -> { broadcast_render_to 'posts', partial: 'v4/posts/destroy', locals: {post: self} }
  after_update_commit -> { broadcast_update_to 'posts', partial: 'v4/posts/post', locals: {post: self} }

  private

  def dont_spam
    last_post = participant.posts.order(:created_at).last

    if last_post && last_post.created_at > Time.current - 1.minute
      errors.add(:base, 'Hey hey! Slow down! Let the others post as well!')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :load_user

  private

  def load_user
    @current_user = cookies[:participant] ? Participant.find_by(uuid: cookies[:participant]) : nil

    unless @current_user
      redirect_to '/participants'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if @current_user
      redirect_to '/v1/posts'
    else
      redirect_to '/participants'
    end
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  skip_before_action :load_user
  before_action :find_user

  def index
    redirect_to '/v1/posts' if @current_user
  end

  def create
    uuid = SecureRandom.uuid

    @participant = Participant.new(username: participant_params[:username], color: "##{SecureRandom.hex(3)}", uuid: uuid)

    if @participant.save
      cookies.permanent[:participant] = uuid

      redirect_to '/v1/posts'
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def participant_params
    params.permit(:username)
  end

  def find_user
    if cookies[:participant]
      @current_user = Participant.find_by(uuid: cookies[:participant])
    end
  end
end

app/controllers/v1/posts_controller.rb
module V1
  class PostsController < ApplicationController
    before_action :load_post, only: %i[edit update destroy]
    before_action :check_ownership, only: %i[update destroy]

    def index
      @posts = Post.order(created_at: :desc)
    end

    def new
      @posts = Post.order(created_at: :desc)
    end

    def create
      @post = Post.new(post_params.merge(participant: @current_user))

      if @post.save
        redirect_to '/v1/posts'
      else
        render '/v1/posts/new', status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @post.update(post_params)
        redirect_to '/v1/posts'
      else
        render '/v1/posts/edit', status: :unprocessable_entity
      end
    end

    def destroy
      @post.destroy!

      redirect_to '/v1/posts'
    end

    private

    def post_params
      params.permit(:text)
    end

    def load_post
      @post = Post.find(params[:id])
    end

    def check_ownership
      if @post.participant != @current_user
        head :forbidden
      end
    end
  end
end

app/controllers/v2/posts_controller.rb
module V2
  class PostsController < ApplicationController
    before_action :load_post, only: %i[show edit update destroy]
    before_action :check_ownership, only: %i[update destroy]

    def index
      @posts = Post.order(created_at: :desc)
    end

    def new
      @posts = Post.order(created_at: :desc)
    end

    def show
      render @post
    end

    def create
      @post = Post.new(post_params.merge(participant: @current_user))

      if @post.save
        redirect_to '/v2/posts'
      else
        render '/v2/posts/new', status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @post.update(post_params)
        render @post
      else
        render '/v2/posts/edit', status: :unprocessable_entity
      end
    end

    def destroy
      @post.destroy!

      redirect_to '/v2/posts'
    end

    private

    def post_params
      params.permit(:text)
    end

    def load_post
      @post = Post.find(params[:id])
    end

    def check_ownership
      if @post.participant != @current_user
        head :forbidden
      end
    end
  end
end

app/controllers/v3/posts_controller.rb
module V3
  class PostsController < ApplicationController
    before_action :load_post, only: %i[show edit update destroy]
    before_action :check_ownership, only: %i[update destroy]

    def index
      @posts = Post.order(created_at: :desc)
    end

    def new
      @posts = Post.order(created_at: :desc)
    end

    def show
      render @post
    end

    def create
      @post = Post.new(post_params.merge(participant: @current_user))

      if @post.save
        respond_to do |format|
          format.turbo_stream
        end
      else
        render '/v3/posts/new', format: :html, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @post.update(post_params)
        render @post
      else
        render '/v3/posts/edit', status: :unprocessable_entity
      end
    end

    def destroy
      @post.destroy!

      respond_to do |format|
        format.turbo_stream
      end
    end

    private

    def post_params
      params.permit(:text)
    end

    def load_post
      @post = Post.find(params[:id])
    end

    def check_ownership
      if @post.participant != @current_user
        head :forbidden
      end
    end
  end
end

app/controllers/v4/posts_controller.rb
module V4
  class PostsController < ApplicationController
    before_action :load_post, only: %i[show edit update destroy]
    before_action :check_ownership, only: %i[update destroy]

    def index
      @posts = Post.order(created_at: :desc)
    end

    def new
      @posts = Post.order(created_at: :desc)
    end

    def show
      render @post
    end

    def create
      @post = Post.new(post_params.merge(participant: @current_user))

      if @post.save
        redirect_to '/v4/posts'
      else
        render '/v4/posts/new', format: :html, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @post.update(post_params)
        render @post
      else
        render '/v4/posts/edit', status: :unprocessable_entity
      end
    end

    def destroy
      @post.destroy!

      head :ok
    end

    private

    def post_params
      params.permit(:text)
    end

    def load_post
      @post = Post.find(params[:id])
    end

    def check_ownership
      if @post.participant != @current_user
        head :forbidden
      end
    end
  end
end

app/controllers/v5/posts_controller.rb
module V5
  class PostsController < ApplicationController
    before_action :load_post, only: %i[show edit update destroy]
    before_action :check_ownership, only: %i[update destroy]

    def index
      @posts = Post.order(created_at: :desc)
    end

    def new
      @posts = Post.order(created_at: :desc)
    end

    def show
      render @post
    end

    def create
      @post = Post.new(post_params.merge(participant: @current_user))

      if @post.save
        redirect_to '/v5/posts'
      else
        render '/v5/posts/new', format: :html, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @post.update(post_params)
        render @post
      else
        render '/v5/posts/edit', status: :unprocessable_entity
      end
    end

    def destroy
      @post.destroy!

      head :ok
    end

    private

    def post_params
      params.permit(:text)
    end

    def load_post
      @post = Post.find(params[:id])
    end

    def check_ownership
      if @post.participant != @current_user
        head :forbidden
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
Every day I'm dooddlin'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VilniusRB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<style> 
.ugly-animation {
  animation-name: example;
  animation-duration: 1s;
}

@keyframes example {
  from {background-color: red;}
  to {background-color: initial;}
}
</style>

  <body>
  <body class="bg-light">
    <%= render 'shared/navigation' %>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/participants/index.html.erb
<div class="d-flex align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
  <%= image_tag 'logo2.png', class: 'me-3', width: 48, height: 48 %>
  <div class="lh-1">
    <h1 class="h6 mb-0 text-white lh-1">Nice header, right?</h1>
  </div>
</div>

<div class="my-3 p-3 bg-body rounded shadow-sm text-center">
  <%= image_tag 'logo2.png', class: 'me-3', width: 200, height: 200 %>
  <h2>Howdy! 👋</h2>
  <h4>Nice to meet you! What is your name?</h4>

  <div class="d-flex align-items-center justify-content-center">
    <div class="">
      <%= form_with url: participants_path, method: :post, class: 'w-100' do |form| %>
        <div class="form-group mb-2">
          <%= form.text_field :username, class: 'form-control', placeholder: '' %>
          <small class="form-text text-danger"><%= @participant&.errors&.messages&.dig(:username)&.join %></small>
        </div>

        <%= form.submit(class: 'btn btn-success') %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="d-flex align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm ugly-animation">
  <%= image_tag 'logo2.png', class: 'me-3', width: 48, height: 48 %>
  <div class="lh-1">
    <h1 class="h6 mb-0 text-white lh-1">Hey, <%= @current_user.username %>!</h1>
    <small>How do you like VilniusRB?</small>
  </div>
</div>

app/views/shared/_nav_link.html.erb
<%= link_to(path, class: "nav-link #{Rails.application.routes.recognize_path(path)[:controller] == controller_path ? 'active' : ''}") { name } %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <div class="container-fluid ugly-animation">
    <span class="navbar-brand">VilniusRB Rocks!</span>
    <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse" data-controller="collapsible-navigation" data-action="collapsible-navigation#open">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= render 'shared/nav_link', name: 'Turbo Drive', path: v1_posts_path %>
        </li>
        <li class="nav-item">
          <%= render 'shared/nav_link', name: 'Turbo Frames', path: v2_posts_path %>
        </li>
        <li class="nav-item">
          <%= render 'shared/nav_link', name: 'Turbo Stream (HTTP)', path: v3_posts_path %>
        </li>
        <li class="nav-item">
          <%= render 'shared/nav_link', name: 'Turbo Stream (WS)', path: v4_posts_path %>
        </li>
        <li class="nav-item">
          <%= render 'shared/nav_link', name: 'Stimulus!', path: v5_posts_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/v1/posts/_post.html.erb
<div class="d-flex text-muted pt-3 ugly-animation">
  <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="<%= post.participant.color %>"/></svg>

  <div class="d-flex justify-content-between border-bottom w-100 pb-3 align-items-center">
    <div class="small lh-sm">
      <strong class="d-block text-gray-dark mb-1">@<%= post.participant.username %></strong>
      <%= post.text %>
    </div>

    <div class="post-actions">
      <% if post.participant == @current_user %>
        <%= link_to(edit_v1_post_path(post), class: 'btn btn-sm btn-info ms-2') { 'Edit' } %>
        <%= link_to(v1_post_path(post), data: {turbo_method: :delete}, class: 'btn btn-sm btn-danger') { 'Delete' } %>
      <% end %>
    </div>
  </div>
</div>

app/views/v1/posts/edit.html.erb
<%= render 'shared/header' %>

<div class="my-3 p-3 bg-body rounded shadow-sm">
  <div class="d-flex justify-content-between align-items-end border-bottom pb-2 mb-0 ugly-animation">
    <h6 class="mb-0">Posts</h6>
    <%= link_to "Back", v1_posts_path, class: 'btn btn-sm btn-secondary' %>
  </div>

  <div class="d-flex text-muted pt-3 ugly-animation">
    <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="<%= @current_user.color %>"/></svg>

    <%= form_with url: v1_post_path(@post), method: :patch, class: 'w-100' do |form| %>
      <strong class="d-block pb-2 mb-0 small lh-sm text-gray-dark">@<%= @current_user.username %></strong>

      <span class="d-block pb-2 mb-0 text-danger fw-bold"><%= @post&.errors&.messages&.dig(:base)&.join %></span>

      <div class="form-group mb-2">
        <%= form.text_field :text, class: 'form-control', placeholder: 'Tell me your thoughts!', value: @post&.text %>
        <small class="form-text text-danger"><%= @post&.errors&.messages&.dig(:text)&.join %></small>
      </div>

      <%= form.submit(class: 'btn btn-success') { 'Save!' } %>
    <% end %>
  </div>
</div>

app/views/v1/posts/index.html.erb
<%= render 'shared/header' %>

<div class="my-3 p-3 bg-body rounded shadow-sm">
  <div class="d-flex justify-content-between align-items-end border-bottom pb-2 mb-0 ugly-animation">
    <h6 class="mb-0">Posts</h6>
    <%= link_to "Add new post", new_v1_post_path, class: 'btn btn-sm btn-info' %>
  </div>

  <%= render @posts %>

  <small class="d-block text-end mt-3 ugly-animation">
    Posts count: <%= Post.count %>
  </small>
</div>

app/views/v1/posts/new.html.erb
<%= render 'shared/header' %>

<div class="my-3 p-3 bg-body rounded shadow-sm">
  <div class="d-flex justify-content-between align-items-end border-bottom pb-2 mb-0 ugly-animation">
    <h6 class="mb-0">Posts</h6>
    <%= link_to "Back", v1_posts_path, class: 'btn btn-sm btn-secondary' %>
  </div>

  <div class="d-flex text-muted pt-3 ugly-animation">
    <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="<%= @current_user.color %>"/></svg>

    <%= form_with url: v1_posts_path, method: :post, class: 'w-100' do |form| %>
      <strong class="d-block pb-2 mb-0 small lh-sm text-gray-dark">@<%= @current_user.username %></strong>

      <span class="d-block pb-2 mb-0 text-danger fw-bold"><%= @post&.errors&.messages&.dig(:base)&.join %></span>

      <div class="form-group mb-2">
        <%= form.text_field :text, class: 'form-control', placeholder: 'Tell me your thoughts!', value: @post&.text %>
        <small class="form-text text-danger"><%= @post&.errors&.messages&.dig(:text)&.join %></small>
      </div>

      <%= form.submit(class: 'btn btn-success') { 'Save!' } %>
    <% end %>
  </div>
</div>

app/views/v2/posts/_header.html.erb
<div class="d-flex align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
  <%= image_tag 'logo2.png', class: 'me-3', width: 48, height: 48 %>
  <div class="lh-1">
    <h1 class="h6 mb-0 text-white lh-1">How do you like VilniusRB?</h1>
    <small>Share your thoughts</small>
  </div>
</div>

app/views/v2/posts/_post.html.erb
<turbo-frame id="<%= dom_id(post) %>">
  <div class="d-flex text-muted pt-3 ugly-animation">
    <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="<%= post.participant.color %>"/></svg>

    <div class="d-flex justify-content-between border-bottom w-100 pb-3 align-items-center">
      <div class="small lh-sm">
        <strong class="d-block text-gray-dark mb-1">@<%= post.participant.username %></strong>
        <%= post.text %>
      </div>

      <div class="post-actions">
        <% if post.participant == @current_user %>
          <%= link_to(edit_v2_post_path(post), class: 'btn btn-sm btn-info ms-2') { 'Edit' } %>
          <%= link_to(v2_post_path(post), data: {turbo_method: :delete, turbo_frame: 'posts'}, class: 'btn btn-sm btn-danger') { 'Delete' } %>
        <% end %>
      </div>
    </div>
  </div>
</turbo-frame>

app/views/v2/posts/edit.html.erb
<%= render 'shared/header' %>

<turbo-frame id="posts">
  <div class="my-3 p-3 bg-body rounded shadow-sm ugly-animation">
    <div class="d-flex justify-content-between align-items-end border-bottom pb-2 mb-0">
      <h6 class="mb-0">Posts</h6>
      <%= link_to "Back", v2_posts_path, class: 'btn btn-sm btn-secondary', data: {turbo_action: 'replace'} %>
    </div>

    <turbo-frame id="<%= dom_id(@post) %>">
      <div class="d-flex text-muted pt-3 ugly-animation">
        <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="<%= @current_user.color %>"/></svg>

        <%= form_with url: v2_post_path(@post), method: :patch, class: 'w-100' do |form| %>
          <strong class="d-block pb-2 mb-0 small lh-sm text-gray-dark">@<%= @current_user.username %></strong>

          <span class="d-block pb-2 mb-0 text-danger fw-bold"><%= @post&.errors&.messages&.dig(:base)&.join %></span>

          <div class="form-group mb-2">
            <%= form.text_field :text, class: 'form-control', placeholder: 'Tell me your thoughts!', value: @post&.text %>
            <small class="form-text text-danger"><%= @post&.errors&.messages&.dig(:text)&.join %></small>
          </div>

          <%= form.submit(class: 'btn btn-success') { 'Save!' } %>
          <%= link_to 'Cancel', v2_post_path(@post), class: 'btn btn-secondary' %>
        <% end %>
      </div>
    </turbo-frame>
  </div>
</turbo-frame>

app/views/v2/posts/index.html.erb
<%= render 'shared/header' %>

<turbo-frame id="posts">
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <div class="d-flex justify-content-between align-items-end border-bottom pb-2 mb-0 ugly-animation">
      <h6 class="mb-0">Posts</h6>
      <%= link_to "Add new post", new_v2_post_path, class: 'btn btn-sm btn-info', data: {turbo_action: 'advance'} %>
    </div>

    <%= render @posts %>

    <small class="d-block text-end mt-3 ugly-animation">
      Posts count: <%= Post.count %>
    </small>
  </div>
</turbo-frame>

app/views/v2/posts/new.html.erb
<%= render 'shared/header' %>

<turbo-frame id="posts">
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <div class="d-flex justify-content-between align-items-end border-bottom pb-2 mb-0 ugly-animation">
      <h6 class="mb-0">Posts</h6>
      <%= link_to "Back", v2_posts_path, class: 'btn btn-sm btn-secondary', data: {turbo_action: 'replace'} %>
    </div>

    <div class="d-flex text-muted pt-3 ugly-animation">
      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="<%= @current_user.color %>"/></svg>

      <%= form_with(url: v2_posts_path, method: :post, class: 'w-100', data: {turbo_action: 'replace'}) do |form| %>
        <strong class="d-block pb-2 mb-0 small lh-sm text-gray-dark">@<%= @current_user.username %></strong>

        <span class="d-block pb-2 mb-0 text-danger fw-bold"><%= @post&.errors&.messages&.dig(:base)&.join %></span>

        <div class="form-group mb-2">
          <%= form.text_field :text, class: 'form-control', placeholder: 'Tell me your thoughts!', value: @post&.text %>
          <small class="form-text text-danger"><%= @post&.errors&.messages&.dig(:text)&.join %></small>
        </div>

        <%= form.submit(class: 'btn btn-success') { 'Save!' } %>
      <% end %>
    </div>
  </div>
</turbo-frame>

app/views/v3/posts/_post.html.erb
<turbo-frame id="<%= dom_id(post) %>">
  <div class="d-flex text-muted pt-3 ugly-animation">
    <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="<%= post.participant.color %>"/></svg>

    <div class="d-flex justify-content-between border-bottom w-100 pb-3 align-items-center">
      <div class="small lh-sm">
        <strong class="d-block text-gray-dark mb-1">@<%= post.participant.username %></strong>
        <%= post.text %>
      </div>

      <div class="post-actions">
        <% if post.participant == @current_user %>
          <%= link_to(edit_v3_post_path(post), class: 'btn btn-sm btn-info ms-2') { 'Edit' } %>
          <%= link_to(v3_post_path(post), data: {turbo_method: :delete}, class: 'btn btn-sm btn-danger') { 'Delete' } %>
        <% end %>
      </div>
    </div>
  </div>
</turbo-frame>

app/views/v3/posts/create.turbo_stream.erb
<turbo-stream action="prepend" target="posts">
  <template>
    <%= render partial: 'post', locals: {post: @post}, formats: [:html] %>
  </template>
</turbo-stream>

<turbo-stream action="update" target="post_count">
  <template>
    <%= Post.count %>
  </template>
</turbo-stream>

<turbo-stream action="update" target="new_post">
  <template>
  </template>
</turbo-stream>

app/views/v3/posts/destroy.turbo_stream.erb
<turbo-stream action="remove" target="<%= dom_id(@post) %>">
</turbo-stream>

<turbo-stream action="update" target="post_count">
  <template>
    <%= Post.count %>
  </template>
</turbo-stream>

app/views/v3/posts/edit.html.erb
<%= render 'shared/header' %>

<turbo-frame id="posts">
  <div class="my-3 p-3 bg-body rounded shadow-sm ugly-animation">
    <div class="d-flex justify-content-between align-items-end border-bottom pb-2 mb-0">
      <h6 class="mb-0">Posts</h6>
      <%= link_to "Back", v3_posts_path, class: 'btn btn-sm btn-secondary' %>
    </div>

    <turbo-frame id="<%= dom_id(@post) %>">
      <div class="d-flex text-muted pt-3 ugly-animation">
        <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="<%= @current_user.color %>"/></svg>

        <%= form_with url: v3_post_path(@post), method: :patch, class: 'w-100' do |form| %>
          <strong class="d-block pb-2 mb-0 small lh-sm text-gray-dark">@<%= @current_user.username %></strong>

          <span class="d-block pb-2 mb-0 text-danger fw-bold"><%= @post&.errors&.messages&.dig(:base)&.join %></span>

          <div class="form-group mb-2">
            <%= form.text_field :text, class: 'form-control', placeholder: 'Tell me your thoughts!', value: @post&.text %>
            <small class="form-text text-danger"><%= @post&.errors&.messages&.dig(:text)&.join %></small>
          </div>

          <%= form.submit(class: 'btn btn-success') { 'Save!' } %>
          <%= link_to 'Cancel', v3_post_path(@post), class: 'btn btn-secondary' %>
        <% end %>
      </div>
    </turbo-frame>
  </div>
</turbo-frame>

app/views/v3/posts/index.html.erb
<%= render 'shared/header' %>

<div class="my-3 p-3 bg-body rounded shadow-sm">
  <div class="d-flex justify-content-between align-items-end border-bottom pb-2 mb-0 ugly-animation">
    <h6 class="mb-0">Posts</h6>
    <div id="actions">
      <%= link_to "Add new post", new_v3_post_path, class: 'btn btn-sm btn-info', data: {turbo_frame: 'new_post'} %>
    </div>
  </div>

  <turbo-frame id="new_post"></turbo-frame>
  <turbo-frame id="posts">
    <%= render @posts %>
  </turbo-frame>

  <small class="d-block text-end mt-3 ugly-animation">
    Posts count: <span id="post_count" data-controller="ugly-animation"><%= Post.count %></span>
  </small>
</div>

app/views/v4/posts/_create.turbo_stream.erb
<turbo-stream action="prepend" target="posts">
  <template>
    <%= render partial: 'v4/posts/post', locals: {post: post}, formats: [:html] %>
  </template>
</turbo-stream>

<turbo-stream action="update" target="post_count">
  <template>
    <%= Post.count %>
  </template>
</turbo-stream>

app/views/v4/posts/index.html.erb
<%= render 'shared/header' %>

<div class="my-3 p-3 bg-body rounded shadow-sm">
  <div class="d-flex justify-content-between align-items-end border-bottom pb-2 mb-0 ugly-animation">
    <h6 class="mb-0">Posts</h6>
    <div id="actions">
      <%= link_to "Add new post", new_v4_post_path, class: 'btn btn-sm btn-info', data: {turbo_frame: 'new_post'} %>
    </div>
  </div>

  <%= turbo_stream_from 'posts' %>
  <turbo-frame id="new_post"></turbo-frame>
  <turbo-frame id="posts">
    <%= render @posts %>
  </turbo-frame>

  <small class="d-block text-end mt-3 ugly-animation">
    Posts count: <span id="post_count" data-controller="ugly-animation"><%= Post.count %></span>
  </small>
</div>